display_name: doudouAI
package_name: doudouai

maintainer:
  name: "daodao97"
  email: ""

priority: optional

section: x11

installed_size: 20000

dependencies:
  - libgtk-3-0
  - libsqlite3-0
  - libsqlite3-dev

essential: false

icon: assets/logo.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Chat
  - AI

generic_name: Chat Client

categories:
  - Development
  - Utility

startup_notify: true
